### PR TITLE
lzmaSDK as framework + swift wrapper

### PR DESCRIPTION
**Pull request by jberkel**
This is a quite big PR with lots of changes, you might not want to merge everything as is, or merge into a separate branch as these changes require iOS 8. Main changes:
- created framework target
- created test target based on previous app code
- fixed compiler warnings
- refactored Objc wrapper
- created a simple Swift wrapper

### CODE REVIEW

**Comment by mdejong** [comment]
To be honest, I am not quite sure what the reason for all these changes is. A swift wrapper could be useful, but it is really only a couple of lines of code. What is the benefit of making the provided example code more complex via multiple targets and so on?

**Comment by jberkel** [comment]
First off, having the code as a framework makes integration into existing iOS projects a lot simpler. Header files and code are packaged up into one bundle which can easily be added to an existing project (it can simply be dragged into an existing project). Moving the example app into a test target makes testing simpler - the tests can be run as part of a continuous integration system or from within Xcode, with direct feedback of which tests have been run and which tests failed.

captura de tela 2015-04-18 00 43 27

The tests link against the dynamic framework, so the main source files don't have to be compiled+linked again (and included in the test target). The whole project configuration becomes simpler as a result.

**Comment by mdejong** [comment]
Yes, in a complex project a split out set of regression tests could be useful. But, this xcode project is just a quick little demo that shows off a couple of lzma features. It is not an extensive set of regression tests built around a TDD dev process. My concern is that these changes might in theory make things slightly easier, but as compared to what? The "integration process" is to just copy the LZMA directory into your iOS project and then you are done. That is about as simple as I could imagine and it works with any version of Xcode without having to mess around with different targets or worry about iOS revisions that the code might work with.

**Comment by jberkel** [comment]
I personally don't like to copy sources from dependencies into my own project. Instead I use [carthage](https://github.com/Carthage/Carthage) to fetch and build the sources for me. Tests might not be extensive right now but that could change. Even if you don't TDD, being able to run them automatically makes a difference.

But as I said in the description there are good reasons why you might not want to integrate these changes.

**Comment by mdejong** [comment]
The other thing I forgot to mention about the framework target is that it does not actually build a FAT binary with both simulator and iOS device executable segments. From your branch:

lzmaSDK.framework > lipo -info lzmaSDK 
Architectures in the fat file: lzmaSDK are: i386 x86_64

**Comment by jberkel** [comment]
when using lzmaSDK via carthage (which i do) this actually gets done automatically

**Comment by mdejong** [comment]
Okay, well I reworked the existing target to be named "lzmaApp" and added a default dynamic iOS 8 Framework target named lzmaSDK. Please let me know if that works for your build needs

**Comment by jberkel** [comment]
ah ok. i will probably keep using my fork for now (since it includes some other fixes) and switch to libcompression when iOS9 ships.

**Pull request closed without merging**
